GENERAL:
  SEED: 123
  WORKER: 8
  SAVE_PREFIX: '.runs'
  EXP_NAME: 'SEDT_T_TIP'

DATA:
  DATA_TYPE: TIP                 # {AIM/UHDM/FHDMi/TIP}
  TRAIN_DATASET: './data_tip/trainData'
  TEST_DATASET: './data_tip/testData'
  DEMO_DATASET: ''
  # TRAIN_LOADER: crop # The loading way for training data, e.g., crop, resize, default; see ./dataset/load_data.py
  # TEST_LOADER: resize # The loading way for testing data, e.g., crop, resize, default; see ./dataset/load_data.py
  # CROP_SIZE: 768 # Set the crop size if LOADER==crop
  # RESIZE_SIZE: 768 # Set the resizing size if LOADER==resize

MODEL:
  MODEL_NAME: 'SEDT'
  ARCH: 'SEDT_T'
  # 선택: 모델 생성자에 그대로 전달할 추가 키-값
  MODEL_KWARGS:
    IMG_SIZE: 256

TRAIN:
  BATCH_SIZE: 12
  SAVE_ITER: 500                 # 학습 중 시각화 저장 주기(이터레이션 단위)
  SAVE_EVERY: 10                 # 체크포인트 주기 저장(에폭 단위). latest는 항상 저장
  START_FRESH: True             # True이면 RESUME='none'일 때 기존 실험 폴더 삭제 후 새로 시작
  RESUME: 'none'                 # {'none','latest','epoch','path'}
  RESUME_EPOCH: 0                # RESUME='epoch'일 때 불러올 에폭
  RESUME_PATH: ''                # RESUME='path'일 때 직접 경로 지정

LOSS:
  LOSS_NAME: 'MultiScaleVGGPerceptualLoss'
  NUM_SCALES: 3
  LAM: 1                         # L1 가중치
  LAM_P: 1                       # Perceptual 가중치

TEST:
  TEST_EPOCH: 'auto'             # {'auto' | 특정 에폭 숫자}; LOAD_PATH 지정 시 무시됨
  SAVE_IMG: False                # {False | 'jpg' | 'png'} 출력 이미지 저장 형식
  LOAD_PATH: '.runs/SEDT_T_TIP/net_checkpoints/checkpoint_latest.tar'  # 체크포인트 경로 지정 시 TEST_EPOCH 무시

SOLVER:
  EPOCHS: 70                     # 총 학습 에폭
  T_0: 10                        # CosineAnnealingWarmRestarts 첫 주기 길이(에폭)
  T_MULT: 1                      # 주기 배수
  ETA_MIN: 0.000001              # 최소 학습률
  BASE_LR: 0.0002                # 초기 학습률
